apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
configMapGenerator:
- name: tensorboard-controller-config
  literals:
  - RWO_PVC_SCHEDULING="True"
  - TENSORBOARD_IMAGE=tensorflow/tensorflow:2.5.1
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  - ISTIO_HOST=*
patchesStrategicMerge:
- patches/add_controller_config.yaml
images:
- name: registry.cn-hangzhou.aliyuncs.com/earl-k8s/docker.io-kubeflownotebookswg-tensorboard-controller
  newName: registry.cn-hangzhou.aliyuncs.com/earl-k8s/docker.io-kubeflownotebookswg-tensorboard-controller
  newTag: v1.9.0-rc.0
